### ISSUE TITLE
Styleguide not rendering components properly

### ISSUE THREAD

**Issue by voutilad** [attivio/suit#2]
Some components don't render and instead display an error:
```
Invariant Violation: You should not use <Route> or withRouter() outside a <Router>
```
![suit invariant violations](https://user-images.githubusercontent.com/9891346/37555568-c5f0c9b6-29bf-11e8-946f-db400582aaab.png)

Components that do render don't have any styling:
![suit rendering issue](https://user-images.githubusercontent.com/9891346/37555577-04c954a0-29c0-11e8-9ebc-7a1340247a74.png)

**Comment by luigivaldez** [comment]
FYI, I am hoping to have the style guide back up and happy by sometime next week.

**Comment by lvaldezattivio** [comment]
The last of the changes to fix to this have all been merged to the master branch.
