### ISSUE TITLE
SUIT breaks when using production minimizers

### ISSUE THREAD

**Issue by voutilad** [attivio/suit#5]
If using production optimizations, like UglifyJS, SUIT functionality breaks. One particular outcome is business center profiles are no longer used.

See #4 for my additions that fix some flawed logic in the `Configurable` component wrapper.

**Comment by luigivaldez** [comment]
Making the change to Configurable.js from your pull request and also adding the display name to all of the existing components as well as our component template for new development.

**Comment by lvaldezattivio** [comment]
The code in Configurable.js has been merged and every component now defines a displayName property. The validation script that will be added shortly also checks to ensure that every future component has this property as well.
